# I - Theoretical Calculations

Here we consider a system made of a capacitor and a josephson junction in series.
This leads to the following hamiltonian for the system :

$$\hat H = 4E_C\hat n^2 - E_J\cos(\hat \varphi)$$

We consider the charge basis, meaning :
$$ \hat n |m\rangle = m|m\rangle$$

Recall that : $$[\hat \varphi, \hat n] = i$$

Let's show using an induction reasoning that : $$[\hat \varphi^k, \hat n] = ki\hat \varphi^{k-1}$$
Suppose that $[\hat \varphi^k, \hat n] = ki\hat \varphi^{k-1}$. Then, we have :

$$
\begin{align}
[\hat \varphi^{k+1}, \hat n] & = \hat \varphi^{k+1} \hat n -  \hat n \hat \varphi^{k+1} \\
& = \hat \varphi^{k} (\hat n \hat \varphi + i) -  \hat n \hat \varphi^{k+1} \\
& = (\hat \varphi^{k} \hat n -  \hat n \hat \varphi^{k})\hat \varphi + i\hat\varphi^k \\
&= (ki\hat \varphi^{k-1})\hat \varphi + i\hat\varphi^k \\
& = (k+1)i\hat \varphi^{k}
\end{align}
$$

From this, we deduce :
$$
\begin{align}
e^{i\hat\varphi}\hat n &= \sum_{k\in\mathbb{N}}{\frac {(i\hat\varphi)^k} {k!}} \hat n\\
&=\sum_{k\in\mathbb{N}}{\hat n \frac {i^k} {k!} \hat\varphi^k} + \sum_{k\in\mathbb{N^*}} \frac {i^k} {k!} ki\hat\varphi^{k-1} \\
&=\hat n \sum_{k\in\mathbb{N}}{\frac {i^k} {k!} \hat\varphi^k} - \sum_{k\in\mathbb{N^*}} \frac {i^k-1} {(k-1)!} \hat\varphi^{k-1} \\
&=\hat n e^{i\hat\varphi} - e^{i\hat\varphi}
\end{align}
$$

Meaning that :
$$e^{i\hat\varphi}\hat n = (\hat n -1)e^{i\hat\varphi}$$

Remeber that : 
$$\hat n = \sum_{k\in\mathbb{Z}}{k |k\rangle\langle k |}$$
Therefore : 
$$e^{i\hat\varphi}\sum_{k\in\mathbb{Z}}{k |k\rangle\langle k |} =(\sum_{k\in\mathbb{Z}}{(k-1) |k\rangle\langle k |})e^{i\hat\varphi} = (\sum_{k\in\mathbb{Z}}{k |k+1\rangle\langle k+1 |})e^{i\hat\varphi} $$

If we evaluate this equation in the following manner, we get :

$$
\begin{align}
\langle q |e^{i\hat\varphi}p|p\rangle &= \langle q | (\sum_{k\in\mathbb{Z}}{k |k+1\rangle\langle k+1 |})e^{i\hat\varphi}|p\rangle \\
&= \sum_{k\in\mathbb{Z}}{k \langle q |k+1\rangle\langle k+1 |}e^{i\hat\varphi}|p\rangle \\
&= (q-1)\langle q| e^{i\hat\varphi} |p \rangle
\end{align}
$$

This expression gives us that $\langle q |e^{i\hat\varphi}|p\rangle = \delta_{p,q-1}$, so we can conclude by saying that :
$$e^{i\hat\varphi} = \sum_{k\in\mathbb{Z}}{\alpha_k |k +1 \rangle\langle k|}$$

Since the basis vectors could be multiplied by any phase, we can then choose (I am not sure I understand why exactly) $\alpha_k = 1 \ \forall k \in \mathbb{Z}$.
Since the cosine is the even part of the exponential, we end up with :

$$
\begin{align}
\cos(\hat \varphi) &= \frac {e^{i\hat\varphi} + e^{-i\hat\varphi}} 2 \\
&= \frac 1 2 \sum_{k\in\mathbb{Z}} |k +1 \rangle\langle k| + |k  \rangle\langle k+1|
\end{align}
$$

To conclude, we have :
$$\boxed{\cos(\hat \varphi) = \frac 1 2 \sum_{k\in\mathbb{Z}} |k +1 \rangle\langle k| + |k  \rangle\langle k+1|}$$

This is what we will implement in the following code.

# II - Implementation using SCQubits

In [1]:
import scqubits as sc

If we realize that this circuit is just a fluxonium with $E_L$ = 0, we get that :

In [16]:
transmon = sc.Transmon(EJ=30.02, EC=1.2, ng=0, ncut=31)

In [17]:
evals_scqubits = transmon.eigenvals()
evals_scqubits -= evals_scqubits[0]
evals_scqubits

array([ 0.        , 15.67283205, 29.77975361, 42.68402237, 49.95162617,
       67.6421301 ])

# III - Implementation using QuTiP

In [11]:
import qutip as qt

In [39]:
def hamiltonian_qt(EC, EJ, truncation_level=31):
    charge = qt.charge(truncation_level, -truncation_level)
    cos_phi = qt.tunneling(2 * truncation_level + 1)

    return 4 * EC * charge * charge - EJ / 2 * cos_phi

In [41]:
evals_qt = hamiltonian_qt(1.2, 30.02).eigenenergies()
evals_qt -= evals_qt[0]
evals_qt

array([   0.        ,   15.67283205,   29.77975361,   42.68402237,
         49.95162617,   67.6421301 ,   68.1083842 ,  100.15339983,
        100.1565223 ,  142.79721928,  142.79722549,  195.30201965,
        195.30201965,  257.52595758,  257.52595758,  329.41232895,
        329.41232895,  410.93468165,  410.93468165,  502.07925725,
        502.07925725,  602.83830762,  602.83830762,  713.20719347,
        713.20719347,  833.18299733,  833.18299733,  962.76380927,
        962.76380927, 1101.94833612, 1101.94833612, 1250.73567691,
       1250.73567691, 1409.12518823, 1409.12518823, 1577.11640064,
       1577.11640064, 1754.70896515, 1754.70896515, 1941.90261786,
       1941.90261786, 2138.69715631, 2138.69715631, 2345.09242301,
       2345.09242301, 2561.08829399, 2561.08829399, 2786.68467059,
       2786.68467059, 3021.88147348, 3021.88147348, 3266.67863832,
       3266.67863832, 3521.07611246, 3521.07611246, 3785.07385248,
       3785.07385248, 4058.67182283, 4058.67182283, 4341.87098

# IV - Implementation using Numpy

In [43]:
import numpy as np
import numpy.linalg as alg

In [47]:
def hamiltonian_np(EC, EJ, truncation_level=31):
    charge = np.zeros((2 * truncation_level + 1, 2 * truncation_level + 1))
    cos_phi = np.zeros((2 * truncation_level + 1, 2 * truncation_level + 1))

    for i in range(2 * truncation_level):
        cos_phi[i, i + 1] = 1
        cos_phi[i + 1, i] = 1
        charge[i, i] = i - truncation_level

    charge[-1, -1] = truncation_level

    return 4 * EC * charge**2 - EJ / 2 * cos_phi

In [49]:
evals_np = np.sort(alg.eigvals(hamiltonian_np(1.2, 30.02)))
evals_np -= evals_np[0]
evals_np

array([   0.        ,   15.67283205,   29.77975361,   42.68402237,
         49.95162617,   67.6421301 ,   68.1083842 ,  100.15339983,
        100.1565223 ,  142.79721928,  142.79722549,  195.30201965,
        195.30201965,  257.52595758,  257.52595758,  329.41232895,
        329.41232895,  410.93468165,  410.93468165,  502.07925725,
        502.07925725,  602.83830762,  602.83830762,  713.20719347,
        713.20719347,  833.18299733,  833.18299733,  962.76380927,
        962.76380927, 1101.94833612, 1101.94833612, 1250.73567691,
       1250.73567691, 1409.12518823, 1409.12518823, 1577.11640064,
       1577.11640064, 1754.70896515, 1754.70896515, 1941.90261786,
       1941.90261786, 2138.69715631, 2138.69715631, 2345.09242301,
       2345.09242301, 2561.08829399, 2561.08829399, 2786.68467059,
       2786.68467059, 3021.88147348, 3021.88147348, 3266.67863832,
       3266.67863832, 3521.07611246, 3521.07611246, 3785.07385248,
       3785.07385248, 4058.67182283, 4058.67182283, 4341.87098